### ISSUE TITLE
Set time limit, get incumbent

### ISSUE THREAD

**Issue by jielu1301** [SCIP-Interfaces/PySCIPOpt#103]
Hi,

I am trying to set the time limit of a problem and get the incumbent before the problem is solved to optimality. Is there any command in PySCIPOPT that is similar to the "set command" in the interactive shell?

Bests,
Jie

**Comment by mattmilten** [comment]
Hi Jie,

to set the time limit (or any parameter in SCIP) you can use the methods `setBoolParam()`, `setIntParam()`, and `setRealParam()`, each with the same parameter name as in the interactive shell, e.g. 

    setIntParam("limits/time", 100)

**Comment by jielu1301** [comment]
Hi Matthias,

Thanks for the response. I placed model.setIntParam("limits/time", 100) before model.optimize. Then it shows the following. Any ideas?

Traceback (most recent call last):
  File "/home/jie/PycharmProjects/Network_Plan/main/SortingPlan.py", line 124, in <module>
    model.setIntParam("limits/time",100)
  File "src/pyscipopt/scip.pyx", line 1739, in pyscipopt.scip.Model.setIntParam (src/pyscipopt/scip.c:61417)
  File "src/pyscipopt/scip.pyx", line 157, in pyscipopt.scip.PY_SCIP_CALL (src/pyscipopt/scip.c:35802)
LookupError: SCIP: the parameter is not of the expected type!

Bests,
Jie

**Comment by fserra** [comment]
Hi, the parameter is not of type integer. You can say that you want to run
for 2.5 seconds. Please try with setRealParam (or something like that, i
don't know the name right now)

On Nov 21, 2017 04:56, "Jie Lu" <notifications@github.com> wrote:

Hi Matthias,

Thanks for the response. I placed model.setIntParam("limits/time", 100)
before model.optimize. Then it shows the following. Any ideas?

Traceback (most recent call last):
File "/home/jie/PycharmProjects/Network_Plan/main/SortingPlan.py", line
124, in
model.setIntParam("limits/time",100)
File "src/pyscipopt/scip.pyx", line 1739, in pyscipopt.scip.Model.setIntParam
(src/pyscipopt/scip.c:61417)
File "src/pyscipopt/scip.pyx", line 157, in pyscipopt.scip.PY_SCIP_CALL
(src/pyscipopt/scip.c:35802)
LookupError: SCIP: the parameter is not of the expected type!

Bests,
Jie

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SCIP-Interfaces/PySCIPOpt/issues/103#issuecomment-345909600>,
or mute the thread

**Comment by jielu1301** [comment]
Thank you very much. The setRealParam("limits/time", 100) call is working.
