### ISSUE TITLE
PySCIPOpt to implement an algorithm based on branch and bound

### ISSUE THREAD

**Issue by wzhuwz** [SCIP-Interfaces/PySCIPOpt#106]
I want to implement an algorithm based on branch and bound to solve an IP. In the directory of examples, this kind of examples cannot be found. I really need an example. Many thanks!

**Comment by fserra** [comment]
what do you mean exactly? Have you checked in the tests directory?

**Comment by wzHuwz** [comment]
I had, but did not found one implementing algorithms with customized branching rules.

**Comment by wzHuwz** [comment]
Thanks. I mean, I need an example implementing algorithms with customized branching rules. For example, a branch-price-and-cut algorithm for VRP.

**Comment by mattmilten** [comment]
Your question is way too vague. We cannot help you if you don't tell us exactly what you want to do.

**Comment by wzHuwz** [comment]
Sorry about that. I want to implement a branch-price-and-cut algorithm to solve the vehicle routing problem, and some special branch rules have to be applied. For example, a node in the B&B tree may have more than two subbranches. Probably, I have to define customized branch rules for my problem. In SCIP several branching rules have been defined, and I would like to know how to apply another branch rule instead of the default one. In addition, whether is it possible to define a new kind of branch rules using PySCIPOpt and if so, how to define one and apply it. Many thanks!

**Comment by fserra** [comment]
Ok. Yes, this is possible. However, I am unsure how many branching methods we have interfaced already.

Some experimental code which uses branching rules and more can be found [here](https://github.com/SCIP-Interfaces/PySCIPOpt/blob/use-probdata-to-store-model/tests/test_coloring.py)

Note that this is not the master branch, but you can get inspired maybe from there. 
It might be that you need some methods that are not yet interfaced, in which case you could do it yourself or ask about them

Hope this helps

**Comment by fserra** [comment]
closed due to inactivity
