### ISSUE TITLE
Segfault when running trySol

### ISSUE THREAD

**Issue by camold** [SCIP-Interfaces/PySCIPOpt#114]
Here is a small example of the segfaults I am currently getting.
Generally, I am trying to set a valid feasible primal solution and provide this to the solver as an initial solution.

Both alternatives produce a segfault (of course you'd only need to run either one).

```python
from pyscipopt import Model

model = Model( "Minimum viable crash" )
model.setMaximize()
model.printVersion() # returns
# SCIP version 4.0.0 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 3.0.0] [GitHash: a80a247]
# Copyright (C) 2002-2017 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)

x1 = model.addVar( vtype="BINARY", name="x1", obj=2 )
x2 = model.addVar( vtype="BINARY", name="x2", obj=1 )
model.addCons( x1 + x2 <= 1 )

# alternative for segfault crash 1
s = model.createSol()
model.setSolVal( s, x1, 0 )
model.setSolVal( s, x2, 1 )
model.trySol( s ) # segfault crash

# alternative for segfault crash 2
model.optimize()
l = model.getSols()
model.trySol( l[0] ) # returns False
model.trySol( l[0] ) # crashes
```

**Comment by fserra** [comment]
Hi, could you please update to SCIP 5.0 and see if it still crashes?

**Comment by fserra** [comment]
Mmm I would guess that this will also be a problem with SCIP 5. The problem seems to be that you can't call trysol at that point in time.

You need to call `addSol`.

Basically, you use `addSol` when you know your solution is feasible. For instance, when you create the model and want to give a starting solution.

In contrast, when you, say, implement a heuristic and want to check that the solution you found is feasible and add it to scip, then you call `trySol`

**Comment by camold** [comment]
Just updated. Same problem.

```python
model.printVersion() 
#SCIP version 5.0.0 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 3.1.0] [GitHash: 3bbd232]
#Copyright (C) 2002-2017 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)
```

I looked up the SCIP documentation which says that trySol (which is what pyscipopt calls) tests the solution for feasibility and adds it to the solution pool.
Not sure why trySol should not work?!?

**Comment by fserra** [comment]
The issue is that SCIP has different stages. For instance, when you just create a SCIP you are in INIT, then when you create a problem you are in PROB, then when you presolve, you are in PRESOLVING, then in SOLVING, etc.

In general, most function can only be called in some stages. In the documentation of `SCIPtrySol` you will see (something like)
```
 *  @pre This method can be called if SCIP is in one of the following stages:
 *       - \ref SCIP_STAGE_TRANSFORMED
 *       - \ref SCIP_STAGE_INITPRESOLVE
 *       - \ref SCIP_STAGE_PRESOLVING
 *       - \ref SCIP_STAGE_EXITPRESOLVE
 *       - \ref SCIP_STAGE_PRESOLVED
 *       - \ref SCIP_STAGE_SOLVING
```

While the stages of `SCIPaddSol` are
```
 *  @pre This method can be called if SCIP is in one of the following stages:
 *       - \ref SCIP_STAGE_PROBLEM
 *       - \ref SCIP_STAGE_TRANSFORMED
 *       - \ref SCIP_STAGE_INITPRESOLVE
 *       - \ref SCIP_STAGE_PRESOLVING
 *       - \ref SCIP_STAGE_EXITPRESOLVE
 *       - \ref SCIP_STAGE_PRESOLVED
 *       - \ref SCIP_STAGE_SOLVING
 *       - \ref SCIP_STAGE_FREETRANS
```

So you see, `trySol` will not work in the problem stage, which is where you are when you set up a model in PySCIPOpt

**Comment by camold** [comment]
Thanks for the explanation. This would explain why trySol crashes right after the initialization of the problem (which is where I use addSol above now).
According to the documentation, however, precondition for trySol is
```
        SCIP_STAGE_TRANSFORMED
        SCIP_STAGE_INITPRESOLVE
        SCIP_STAGE_PRESOLVING
        SCIP_STAGE_EXITPRESOLVE
        SCIP_STAGE_PRESOLVED
        SCIP_STAGE_SOLVING
```
Since also trySol does not crash at the first call (trySol(l[0])) I assume this is the right phase. Why would it crash when calling twice?

**Comment by fserra** [comment]
nope, is not the right stage. That stage is the solved stage. Why it
doesn't crash the first time is the question. But the answer I don't know.

**Comment by camold** [comment]
You're right. trySol should never be callable before or after, due to specification. Hence, the issue is clarified.
