### ISSUE TITLE
Understanding of constraint handler

### ISSUE THREAD

**Issue by Ou-Ou** [SCIP-Interfaces/PySCIPOpt#250]
I am trying to write a constraint handler myself. It looks like test_tsp example is the only reference I could check. I am wondering how this process work.
My understanding is that, in the tsp problem. First, we solve the model without the sub-tour elimination constraints. Then, with current solution, we check whether there is a violation (sub-tour) or not. If so, we add the violated constraint into the model and solve it again.
However, in the example, by using the constraint handler. It seems like it solves the problem only once. Is that coincidence or this is exact how constraint handler work?

Thanks a lot

**Comment by mattmilten** [comment]
The problem is only solved once - why should you solve it several times ;-)

The trick is indeed that the constraint handler represents additional constraints that are added step by step during the solving process. This is necessary because for TSP there are exponentially many subtour elimination constraints that cannot possibly be added right from the start. You can imagine this like your problem is changing over time until enough actual constraints were added to satisfy the conditions of the TSP constraint handler.
