### ISSUE TITLE
GLIBC and older versions

### ISSUE THREAD

**Issue by tomsons22** [SCIP-Interfaces/PySCIPOpt#276]
Hi,

I'm trying to get SCIP with the interface working on a cluster (Linux), to which I don't have sudo  access. I was able to get everything working in my local computer.

I downloaded the "SCIPOptSuite-6.0.1-Linux.sh" file, and extracted it in a local directory in the head node of the cluster. Then I did  "export SCIPOPTDIR=<path_to_install_dir>" with the correct path to install dir. Finally I installed using "pip install pyscipopt". When running code in the cluster I get the following error:

ImportError: /lib64/libc.so.6: version `GLIBC_2.22' not found (required by /path_to_install/SCIPOptSuite-6.0.1-Linux/lib/libscip.so.6.0)

Apparently the cluster has GLIBC_2.17. I had two ways of dealing with this in mind:
1- Try to get a newer version of GLIBC locally, which seems really messy.
2- Try to use an older version of SCIP, hoping that it'll require a previous version of GLIBC. I downloaded "SCIPOptSuite-5.0.1-Linux.sh", removed the old folder, uninstalled the interface, extracted the 5.0.1 version, updated the "export SCIPOPTDIR=<path_to_install_dir>" with the directory of the 5.0.1 version. However, when I try to run something, I get the error 

ImportError: libscip.so.6.0: cannot open shared object file: No such file or directory

which makes sense, since I don't have version 6.0 anymore (but I do have 5.0.1 now...). My questions are, is pyscipopt looking for the latest version of SCIP (6.0) automatically (If so, can I change this)? What older version would I be able to run with GLIBC_2.17? Or more general, do you have any recommendations on how to figure this out?

Thanks!
Tomas

**Comment by mattmilten** [comment]
The most straightforward way of solving this problem is to compile the SCIPOptSuite on the target machine. Please refer to the installation instructions in the SCIP documentation.

Unfortunately, it is quite difficult/annoying to build a completely static binary/library package. We try to put in as much as possible, e.g. Ipopt, gmp, etc. In the end, though, there is still the basic libc dependency that is also subject to change every few years.

I cannot recommend to use an older version of either SCIP or PySCIPOpt.
