### ISSUE TITLE
Imposible to catch a Var Event

### ISSUE THREAD

**Issue by boiro9** [SCIP-Interfaces/PySCIPOpt#284]
I am trying to implement an event handler to know how at every node of the branch and bound tree, what is the branching var and how its bounds have been modified. To this aim, I defined an event handler following the test_event.py example (in the tests folders), but using  the catchVarEvent method. The code crashed without given any information about the problem, I know that it is because of the catchVarEvent, since if I change it by a catchEvent it works. I would really apprecciate any help with this. 

The code I use is the following:

```python
from pyscipopt import Model, Eventhdlr, SCIP_RESULT, SCIP_EVENTTYPE, SCIP_PARAMSETTING, quicksum

calls = []

class MyEvent(Eventhdlr):
    
    def __init__(self, var):
        self.var = var
    
    def eventinit(self):
        calls.append('eventinit')
        var_trans = self.model.getTransformedVar(self.var)
        self.model.catchVarEvent(var_trans, SCIP_EVENTTYPE.UBTIGHTENED, self)
        #self.model.catchEvent(SCIP_EVENTTYPE.NODEBRANCHED, self)

    def eventexit(self):
        calls.append('eventexit')
        self.model.dropVarEvent(self.var, SCIP_EVENTTYPE.UBTIGHTENED, self)

    def eventexec(self, event):
        calls.append('eventexec')
        print('NODE: ', event.getNode().getNumber())
        print("Type: ", event.getType())
        print('New Bound: ',event.getNewBound())
        print('Old Bound: ',event.getOldBound())
        # Save the branching var and the bound that have been modified

calls = []

# create solver instance
m = Model()
#s.hideOutput()
m.setPresolve(SCIP_PARAMSETTING.OFF)
m.setIntParam("presolving/maxrounds", 0)
m.setRealParam("limits/time", 60)

# Defining the vars:
x0 = m.addVar(lb=-2, ub=4)
r1 = m.addVar()
r2 = m.addVar()
y0 = m.addVar(lb=3)
t = m.addVar(lb=None)
l = m.addVar(vtype="I", lb=-9, ub=18)
u = m.addVar(vtype="I", lb=-3, ub=99)

# Defining the constraints
more_vars = []
for i in range(1000):
    more_vars.append(m.addVar(vtype="I", lb= -12, ub=40))
    m.addCons(quicksum(v for v in more_vars) <= (40 - i) * quicksum(v for v in more_vars[::2]))

for i in range(1000):
    more_vars.append(m.addVar(vtype="I", lb= -52, ub=10))
    m.addCons(quicksum(v for v in more_vars[50::2]) <= (40 - i) * quicksum(v for v in more_vars[405::2]))

m.addCons(r1 >= x0)
m.addCons(r2 >= -x0)
m.addCons(y0 == r1 +r2)
#m.addCons(t * l + l * u >= 4)
m.addCons(t + l + 7* u <= 300)
m.addCons(t >= quicksum(v for v in more_vars[::3]) - 10 * more_vars[5] + 5* more_vars[9])
m.addCons(more_vars[3] >= l + 2)
m.addCons(7 <= quicksum(v for v in more_vars[::4]) - x0)
m.addCons(quicksum(v for v in more_vars[::2]) + l <= quicksum(v for v in more_vars[::4]))

# Defining the objective function
m.setObjective(t - quicksum(j*v for j, v in enumerate(more_vars[20:-40])))

# Adding the event handler
var = t
eventhdlr = MyEvent(var)
m.includeEventhdlr(eventhdlr, "TestUBTightened", "python event handler to catch UBTightened")

# solve problem
m.optimize()


```

**Comment by fserra** [comment]
Hi @boiro9. This has been a busy week, I will try to have a look at this next week

**Comment by fserra** [comment]
Hi @boiro9 

This is a bit tricky. In SCIP not all events allow you to access the same information. The problem here is that the var event doesn't have a getNote(). I was checking and we didn't copy the documentation of available in SCIP for the event methods.

In SCIP it says

```
/** gets node for a node or LP event */
SCIP_NODE* SCIPeventGetNode(
   SCIP_EVENT*           event               /**< event */
   )
```

This is why calling getNode for an event of type `SCIP_EVENTTYPE.NODEBRANCHED` works.

One thing you can do is to store the model in your Event class and then use it to call `getCurrentNode`.
However, the event `SCIP_EVENTTYPE.UBTIGHTENED` will be called for every tightening and not only for tightenings due to branching.

I think that right now is not possible to do what you want. I think the proper way of obtaining the information you want is something like the following:

1. Catch the event NODEBBRANCHED
2. Get the node
3. Get the children of the (focused) node (which I hope is still the one branched on) with `SCIPgetChildren`
4. Then ask each child for their number of domain changes with `SCIPnodeGetNDomchg` and get the number of branchings (I am not sure whether this information is going to be available at this point, but I guess it should)
5. Get the actual domain changes with `SCIPnodeGetDomchg`
6. Look in there which variable's domain got changed due to branching.

Several points. Most of the functions above are not wrapped, but more importantly, some of the data structures are not wrapped.  
I know that this is overly complicated, but SCIP allows you to create very general branching rules and so the functions and data structures are more complicated than the ones one would need if only binary branching is supported.

Anyway, I am also not sure whether it would work.

It would take us some time to wrap all this information. But if you want to give it a try you can start with some and open a pull request.

Just in case I am over complicating things (there might be a magic function I am not aware of), @mattmilten  do you think there is an easier way?

**Comment by fserra** [comment]
reopen if there is still a problem
