### ISSUE TITLE
Custom constraint with LP relaxation

### ISSUE THREAD

**Issue by bgrimstad** [SCIP-Interfaces/PySCIPOpt#294]
Hi, 

First, I would like to thank you for providing a Python API to SCIP. I think the community needs more open-source codes for optimization.

I have just started experimenting with the API by implementing a separator. The Gomory cuts example was helpful and the separator seems to work as expected.

As my next project I was planning to implement a custom constraint type on the form: 
`f(x) = y`,
where `f` is a complicated function that can be evaluated and bounded, but not coded explicitly using the supported operators. I was planning to use the bounds to create an LP relaxation of `f`. I am not sure if I should use a constraint handler or a relaxator abstraction for this. I could not find any examples of the latter. 

I would need the ingredients to incorporate such constraints in the spatial branch-and-bound scheme of SCIP:
- Evaluation of `f(x)` and, if possible, its gradient at `x` (for upper bounding problems)
- Specification of LP relaxations of `f` (for lower bounding problems)
- Specification of `x` as (spatial) branching variables

Look forward to hear from you. And again, thank you for your contributions.

Kind regards,
Bjarne

**Comment by fserra** [comment]
Hi

A constraint handler should do. There is an "example" in test_alldiff. You can also have a look at https://scip.zib.de/doc/html/CONS.php for some of the terms and what each callback is supposed to do.

**Comment by bgrimstad** [comment]
Thank you. The constraint handler seems to provide the needed functionality. 

I will report back if I get around to implementing a useful example.

**Comment by bgrimstad** [comment]
Hi.

I have a couple of follow-up questions. With reference to the documentation you linked to:

- Is it true that branching is performed in the CONSENFOLP function via the return flag SCIP_BRANCHED? Does this mean that the constraint handler is responsible for branching? In that case, are branching priorities handled outside of the constraint handler?
- I cannot seem to find a way to return the gradient of the nonlinear constraint at some point x. How can I supply constraint gradients when solving NLP relaxations?

Kind regards,
Bjarne

**Comment by fserra** [comment]
Hi

Usually branching is performed by the branching rule, but in some cases, a constraint handler might branch, either because it might know a better way of branching (e.g. sos1 constraints https://scip.zib.de/doc/html/cons__sos1_8c.php#aa2bded9b22b1dd6022827b1e01e571f8 )
or out of desperation, (e.g. cons_quadratic ).

Usually, though, nonlinear constraint handler suggests which variable to branch on with the function `SCIPaddExternBranchCand`. I couldn't really find documentation on adding external branching candidates, but you can have a look at cons_quadratic.c. The documentation of `SCIPaddExternBranchCand` is here https://scip.zib.de/doc/html/group__PublicBranchingMethods.php#gaf8f111a4eba5256e52bbf5d75af4c456

This function is not yet part of the interface, but adding it is no problem.

Regarding the gradients, this is tricky. I do not think this is currently possible. SCIP uses CppAD to compute gradients, but I think it might support adding a specific user expression for which one might be able to specify the derivative directly. However, none of this is supported at the moment in pyscipopt and I don't think it is going to be supported since we are rewriting the way scip handles nonlinear expressions. Maybe @mueldgog  or @svigerske might know a trick to get around this?

Note, however, that SCIP uses gradient information only for primal heuristics, so if you know any decent solution in advance, it might not be too bad.
