### ISSUE TITLE
Segfault when assessing dual variables

### ISSUE THREAD

**Issue by joaopedroso** [SCIP-Interfaces/PySCIPOpt#30]
Trying to assess dual solution in some cases segfaults; e.g., when executing the program attached.
[tmp.txt](https://github.com/SCIP-Interfaces/PySCIPOpt/files/393636/tmp.txt)

**Comment by fserra** [comment]
Hey Joao

an assert is failing  
(BTW you can run in debug mode if you compile the scipoptsuite with OPT=dbg and then uncomment the line
```python
#extra_compile_args=['-UNDEBUG'],   # use this when linking to a dbg libscipopt.so
```
in setup.py)

In principle, one don't have access to dual information after solving an LP from SCIP: see http://scip.zib.de/#faq Can I use SCIP as a pure LP-Solver?  
But I don't really understand what is going on here, because the assert that fails is that `cons != NULL`, where `cons` is the transformed constraint of `Order(0)`, which as far as I can see shouldn't be NULL.

I'll investigate this further

**Comment by fserra** [comment]
hi @joaopedroso 

looking again into this issue. your models looks like
```
STATISTICS
  Problem name     : master LP
  Variables        : 7 (0 binary, 0 integer, 0 implicit integer, 7 continuous)
  Constraints      : 7 initial, 7 maximal
OBJECTIVE
  Sense            : minimize
VARIABLES
  [continuous] <x(0)>: obj=1, original bounds=[0,+inf]
  [continuous] <x(1)>: obj=1, original bounds=[0,+inf]
  [continuous] <x(2)>: obj=1, original bounds=[0,+inf]
  [continuous] <x(3)>: obj=1, original bounds=[0,+inf]
  [continuous] <x(4)>: obj=1, original bounds=[0,+inf]
  [continuous] <x(5)>: obj=1, original bounds=[0,+inf]
  [continuous] <x(6)>: obj=1, original bounds=[0,+inf]
CONSTRAINTS
  [linear] <Order(0)>:  +4<x(0)>[C] >= 4;
  [linear] <Order(1)>:  +3<x(1)>[C] >= 2;
  [linear] <Order(2)>:  +2<x(2)>[C] >= 6;
  [linear] <Order(3)>: <x(3)>[C] >= 6;
  [linear] <Order(4)>: <x(4)>[C] >= 2;
  [linear] <Order(5)>: <x(5)>[C] >= 2;
  [linear] <Order(6)>: <x(6)>[C] >= 2;
END
```

and it seems that there is an issue in SCIP with constraints that are bounds. It seems that even if presolve is off, they get removed and so you can't access their dual multipliers

@mattmilten what should happen at the end? In the meantime we could check whether the constraint has consists of a single variable and then return its reduce cost?

**Comment by mattmilten** [comment]
Jakob implemented a new user method to query the dual values of original constraints - including bound constraints. We can use this only in the next SCIP release, though. In the meantime we have to either implement the same code in PySCIPOpt or just wait.

**Comment by mattmilten** [comment]
This has been fixed already.
