### ISSUE TITLE
how to use a function in SCIP?

### ISSUE THREAD

**Issue by naghmeh6** [SCIP-Interfaces/PySCIPOpt#343]
I need to use a function in SCIP, called: SCIPgetGeneratorsSymmetry(). actually I need to find the generators of the symmetry group of an ILP. I know I have to run a c file to use this function.

I get error when I run the code

symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mueldgog** [comment]
I can imagine that you feel desperate, but your issue has nothing to do with PySCIPOpt. Anyway, you decided on using Makefile instead of CMake. If you do so, then you need to add `-DNO_CONFIG_HEADER` to your gcc command because of this config.h file is only generated when using CMake.

An alternative: Why don't you just overwrite the content of `src/main.c` (in the SCIP directory) to your needs? In this case, after successfully compiling SCIP, you can run your code by executing `./bin/scip`.

**Comment by naghmeh6** [comment]
could you please explain it more? I am vary new in c and scip. what I have to do `src/main.c`? 
Thank you so much in advanced

**Comment by mueldgog** [comment]
Right now, you seem to struggle with linking to libscip. So instead of writing your own main.c, you just modify the one in SCIP. Then you don't need to take care of the linking etc. and just use our Makefile (or CMake) system.

**Comment by naghmeh6** [comment]
how I can modify my Makefile? this is what I am trying to do:

I have a .mps file. it is an ILP which has symmetry. I want to find generators of the symmetry group this problem.
So I need to run SCIPgetGeneratorsSymmetry() of this mps file. Could you please tell me what I should do?
