### ISSUE TITLE
test suite failures (GIT version 2016/08/20)

### ISSUE THREAD

**Issue by HJarausch** [SCIP-Interfaces/PySCIPOpt#35]
I get the following test suite failures on my Gentoo system.
PySCIPOpt has been compiled from GIT (on 2016/08/20)
I have version 3.2.1 of the scipoptsuite installed here.

test_alldiff.py

Traceback (most recent call last):
  File "test_alldiff.py", line 286, in <module>
    test_main()
  File "test_alldiff.py", line 267, in test_main
    scip, x = create_sudoku()
  File "test_alldiff.py", line 225, in create_sudoku
    domains[var] = vals
TypeError: unhashable type: 'pyscipopt.scip.Variable'

--------------------

test_memory.py

Traceback (most recent call last):
  File "test_memory.py", line 19, in <module>
    test_not_freed()
  File "test_memory.py", line 7, in test_not_freed
    pytest.skip()
  File "/usr/lib64/python3.5/site-packages/_pytest/runner.py", line 468, in skip
    raise Skipped(msg=msg)
Skipped: <Skipped instance>

--------------------

test_short.py   -- where are the files check/testset/short.{test,solu} ???

Traceback (most recent call last):
  File "test_short.py", line 17, in <module>
    pytest.skip("Files for testset `short` not found (symlink missing?)")
  File "/usr/lib64/python3.5/site-packages/_pytest/runner.py", line 468, in skip
    raise Skipped(msg=msg)
Skipped: Files for testset `short` not found (symlink missing?)

**Comment by fserra** [comment]
test_alldiff should be move to an example or something.

The files are in the scipoptsuite/scip

I don't understand the problem with test_memory

Thanks!

**Comment by HJarausch** [comment]
"test_alldiff should be move to an example or something."

What does that mean?

Can I use the class ALLDIFFconshdlr in my own code to force all integer variables to be different?
Thanks!

**Comment by fserra** [comment]
Oh, that was just a note for myself.

Yes, you can, but I believe the code is not complete. For instance, it doesn't implement branching.

**Comment by fserra** [comment]
@leethargo do you remember why Variables are not hashable any more??

**Comment by fserra** [comment]
the error you get from test_memory seems to be from py.test (?)  
which version are you using?

**Comment by leethargo** [comment]
Sorry about the failing test. Another case of a test which is skipped because of missing dependencies (networkx, matplotlib).

@fserra: `Variable` is not hashable because we already use the `==` operator on it to create constraints.

The test also takes a while until it fails. Should it be disabled for now?

**Comment by fserra** [comment]
Oh I see, thanks

For me at least, it doesn't take any time before the fail. So the test worked when Variables were hashable since the code builds a dictionary between variables and their domain. I just need to fix this, but now am unsure on how to do the mapping.  
Also, I am unsure whether this should be a test (and simplify dependencies, for instance one doesn't really need matplotlib), or should we move it to an example... Well, once we have a decent set of test we should definitely move it to an example.

**Comment by leethargo** [comment]
Why don't you use the variable's `name` as the key for your `dict`?

**Comment by fserra** [comment]
because we nowhere enforce that names are unique. I was thinking to just extend the class, but we have the `ptr` of a var which we can use as key

@HJarausch I have to retract my words. I don't believe this code is going to work on a complex problem.

**Comment by fserra** [comment]
eb4792d fixes the test

**Comment by HJarausch** [comment]
I have py.test version 2.8.7

PySCIPOpt doesn't implement operator != - why?
I need an all-different condition, but without operator != (not equal) I cannot code a simple one.
Or is there a method to negate a constraint?
Thanks,
Helmut

**Comment by leethargo** [comment]
In general, MIP solvers don't support `!=` constraints. The same with `<` and `>`.
