### ISSUE TITLE
How to install it on Windows?

### ISSUE THREAD

**Issue by ahuman** [SCIP-Interfaces/PySCIPOpt#36]
the INSTAll.md introduces the installing process on Linux, I wonder how to install it on Windows. looking forward to your reply, thank you very much.

**Comment by ahuman** [comment]
the INSTAll.md introduces the installing process on Linux, I wonder how to install it on Windows. looking forward to your reply, thank you very much.

**Comment by mattmilten** [comment]
Unfortunately, Windows is currently not supported. We did not yet find a way to make it work. We would be happy to accept your pull request in case you know how to do it!

**Comment by fserra** [comment]
I heard a rumor that it might be possible to install it in windows now??

**Comment by stan227** [comment]
For me it worked with Python 3.5.2 (also tried Python 2.7, but that did not work). I tried the 32-bit binary of Python, i.e. did not test 64-bit, but it may work as well.

1. Install Python 3.5.2 32bit.
2. Install setuptools using pip: `pip install setuptools` (use an **elevated** prompt).
3. Install Visual Studio Community 2015.
4. Download the SCIP library for Windows/PC, 32bit, msvc 14.0 from http://scip.zib.de/#download. You will need the files _libscip-3.2.1.mingw.x86.msvc.opt.spx.lib_ and _libscip-3.2.1.mingw.x86.msvc.opt.spx.dll_ from the zip archive.
5. In your PySCIPOpt directory, copy _libscip-3.2.1.mingw.x86.msvc.opt.spx.lib_ to the _lib_ subdirectory.
6. Copy the attached
[mysetup.txt](https://github.com/SCIP-Interfaces/PySCIPOpt/files/594935/mysetup.txt) to your PySCIPOpt directory and rename it to _mysetup.py_. (It is basically the original setup file with distutils replaced by setuptools, the environment variable stuff commented out and runtime_library_dirs removed.)
7. From your Windows kickoff menu, open Visual Studio 2015 x86 Native Tools Commandline. (This will
set up some environment variables correctly for the compilation of the cython module. If you later get an error like _"unable to find vcvarsall.bat"_, you failed on this one.) Go to your PySCIPOpt folder `cd C:\path\to\PySCIPOpt` and run `python mysetup.py install --user`. (If you used an elevated command prompt, you could skip the `--user` and install PySCIPOpt for all users.)
8. Copy _libscip-3.2.1.mingw.x86.msvc.opt.spx.dll_ to a folder in your PATH variable or to the directory where your python script is located and try using your application.

Good luck!

**Comment by oakBranch** [comment]
I would like to be able to install it on Windows 7 (Pro, 64-bit with Anaconda Python 3.5 distribution). I work in a research government organisation and our software policies are very strict and would not allow me so much fiddling as suggested above. Hence, a simpler option would be great.
I am an economist and know about optimisation but not enough about application development to start a new pull request. However, what do you think about compiling your code for windows x86 & x64 targets so that the interface could be used with the pre-compiled binaries supplied by ZIB SCIP?

**Comment by mattmilten** [comment]
There will be a new release of the SCIP Optimization Suite soon and we will also adapt PySCIPOpt accordingly. The installation process is about to become more straight forward. Please be patient for around 2 more weeks.

**Comment by oakBranch** [comment]
Thank you very much! A lot of us (non-programmers) out there really appreciate all the work done by open source community! Given a serious and prolonged budget squeeze on the UK public sector we are left with no money to spend on any fancy commercial solvers. Hence, this project does help.

**Comment by talkaminker** [comment]
I also need this to work on Mac and Windows. if it will be installeble from pip or conda this will be awesome

**Comment by JSergioMartins** [comment]
Stan227, I am stuck on step 5. In which directory should PySCIPOpt be?

**Comment by stan227** [comment]
JSergioMartins: It does not matter where you put your PySCIPOpt directory. This directory is only used to build and install PySCIPOpt. Note that I now inserted step 5a into my older comment (that is something I forgot to mention). Say that you put PySCIPOpt into your home directory, it has a subfolder _pysciptopt_. You have to put some source and header files from SCIP into this subdirectory, so that the installer can find them.

**Comment by talkaminker** [comment]
wouldn't it be more beneficial for all if everything will be pip installable? (or conda).
today with wheels it should be pretty easy. 
Currently I am using the conda install i found which works for linux. my friend can't use it because he has windows and installing something which is not through pip or conda is just too much of a hassle for him.

**Comment by mattmilten** [comment]
I completely agree. And since PySCIPOpt is open source I'd be happy to accept your pull request to simplify the installation. Your friend might want to have look at docker, the Windows 10 Bash or even a proper Linux virtual machine. It is my impression that Python development on Windows is not that straightforward and I'm not very experienced on this platform, so any help is much appreciated.

**Comment by mattmilten** [comment]
It should work now. Just do pip install pyscipopt

**Comment by JSergioMartins** [comment]
Great!!!!

**Comment by wzHuwz** [comment]
I really need an example which implements an algorithm based on branch and bound. Need your help
