### ISSUE TITLE
readProblem required plugin not found

### ISSUE THREAD

**Issue by IngoMeise** [SCIP-Interfaces/PySCIPOpt#365]
Hi all,

i would like to read a problem from an external zpl file with .readProblem. I did:

model = Model()
file = open("pathtofile","r")
model.readProblem("file")

Unfortunately, the following error occurs: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyscipopt/scip.pyx", line 4040, in pyscipopt.scip.Model.readProblem
  File "src/pyscipopt/scip.pyx", line 241, in pyscipopt.scip.PY_SCIP_CALL
Exception: SCIP: a required plugin was not found !

I suspect that i am doing something wrong here but i don t know how to import the file, otherwise. Maybe, it is some missing plugin installation, though.

Thanks for helping me!

**Comment by fserra** [comment]
mmm I guess this is because your SCIP is compiled without ZIMPL support. How did you install SCIP?

A couple of alternatives: 
You can also use zimpl itself to generate another type of file (lp, etc).
You can also write your model directly on pyscipopt.

**Comment by IngoMeise** [comment]
Thanks for the quick response! 

I just installed the scipoptsuite. I downloaded the zpl from a website as i didn t want to install ZIMPL. Is it possible to create an lp file in a text editor or do you know about test instances to download? I need to test whether the code works if i get the information from an external file and i have already testet the implementation where i get the information from another pyscipopt model or from lists etc.

**Comment by IngoMeise** [comment]
I just installed the SCIPOptSuite-6.0.x.sh file in order to install pyscipopt. Haven t used SCIP or ZIMPL, yet.

**Comment by fserra** [comment]
oh. I see. I guess small problems can be found in http://miplib2010.zib.de/miplib3/miplib3.html
Alternatively, you can write you pyscipopt model to a file: model.writeProblem() and then read the written problem.

BTW, I just realized that I don't understand your code. Why do you call open before calling readProblem? and what is the value of "file"?

**Comment by IngoMeise** [comment]
Thanks a lot! I thought that the file has to be loaded into python before as the description of .readProblem indicates that the argument has to be the file. Unfortunately, the few lines of code using .readProblem which can be found by google don t use the path as the argument, neither. model.readProblem("pathtofile") works, now. Should have tried that earlier!

**Comment by fserra** [comment]
I see. I tried to improve the docu with 56543d8

**Comment by adamzsl** [comment]
So how did you manage to solve the issue? I happen to have the same problem and solving it was/still is a long path.

`
from pyscipopt import Model

model = Model()
model.readProblem("path\\file.zpl")
model.optimize()

`

`
  File "src\\pyscipopt\\scip.pxi", line 5353, in pyscipopt.scip.Model.readProblem
    Parameters
  File "src\\pyscipopt\\scip.pxi", line 287, in pyscipopt.scip.PY_SCIP_CALL
    elif rc == SCIP_PLUGINNOTFOUND:
`
    
I get the error above, even though zpl files are listed as supported in the documentation (https://pyscipopt.readthedocs.io/en/latest/tutorials/readwrite.html).
When I use file.mps it works

There is function `SCIPincludeReaderZpl()` (https://www.scipopt.org/doc/html/reader__zpl_8h.php), but i dont know how to include it because the source file of that function is in C and i use python.

Do you know what should I do to import that function? I think it will be the proper way of handling zpl files.

**Comment by adamzsl** [comment]
So how did you manage to solve the issue? I happen to have the same problem and solving it was/still is a long path.

```
from pyscipopt import Model
model = Model()
model.readProblem("path\\file.zpl")
model.optimize()
```

`
  File "src\\pyscipopt\\scip.pxi", line 5353, in pyscipopt.scip.Model.readProblem
    Parameters
  File "src\\pyscipopt\\scip.pxi", line 287, in pyscipopt.scip.PY_SCIP_CALL
    elif rc == SCIP_PLUGINNOTFOUND:
`
    
I get the error above, even though zpl files are listed as supported in the documentation (https://pyscipopt.readthedocs.io/en/latest/tutorials/readwrite.html).
When I use file.mps it works

There is function `SCIPincludeReaderZpl()` (https://www.scipopt.org/doc/html/reader__zpl_8h.php), but i dont know how to include it because the source file of that function is in C and i use python.

Do you know what should I do to import that function? I think it will be the proper way of handling zpl files.

**Comment by Joao-Dionisio** [comment]
Hey @adamzsl! I'm not too familiar with this, but it looks like you need to include ZIMPL. Look at this note:

![image](https://github.com/user-attachments/assets/10cc08b3-3506-45bd-b8f7-244b8d5f84b4)

I imagine this is done with the [includeReader](https://scipopt.github.io/PySCIPOpt/docs/html/classpyscipopt_1_1scip_1_1Model.html#abdd87d85cc59a5d239e512db1ceafc91) method, and that you probably need to install ZIMPL yourself

**Comment by adamzsl** [comment]
How should I use that function? When i run code below I get all zeros. 

It's mixed with one from tests\test_reader.py, but in test_reader method readerread() is customised for specific input, is there a way to make it universal to all zimpl/zpl files, for when i have to read whole table of nutrients?

```
from pyscipopt import Model,Reader, SCIP_RESULT

class ZPLReader(Reader):
    def readerread(self, filename):
        with open(filename, "r") as f:
            # Read the ZPL file and create the model
            pass
        return {"result": SCIP_RESULT.SUCCESS}

model = Model()
reader = ZPLReader()
model.includeReader(reader, "zplreader", "ZPL file reader", "zpl")
model.readProblem("path\\test.zpl")
model.optimize()
```

Also what do you mean by install ZIMPL by myself? When i click on, it redirect me to PySCIPOpt which is this whole program.
This comment even says that I can run ZIMPL without installing anything (https://stackoverflow.com/a/25864546/27671013)
My versions are compatibile (SCIP 9.1.0 and PySCIPOpt 5.1.1)
