### ISSUE TITLE
Can I use ExprCons for model.addConsNode()?

### ISSUE THREAD

**Issue by purin0604** [SCIP-Interfaces/PySCIPOpt#391]
Hi,

I would like to add some constraints locally using model.addConsNode().
(Set some variables to be zero. )
From coloring examples and documents, I learned it should be something like:

```
Class myConshdlr(Conshdlr):

    def consprop(self, constraints, nusefulconss, nmarkedconss, proptiming):
         for var in self.model.vars:      
               if condition is True:
                  self.model.chgVarUb(var, 0.0)
        return {"result": SCIP_RESULT.DIDNOTFIND}

    # fundamental callbacks 
    def consenfolp(self, constraints, nusefulconss, solinfeasible):
        return {"result": SCIP_RESULT.FEASIBLE}
    def conscheck(self, constraints, solution, checkintegrality, checklprows, printreason):
        return {"result": SCIP_RESULT.FEASIBLE}
    def conslock(self, constraint, nlockspos, nlocksneg):
        return {"result": SCIP_RESULT.FEASIBLE}

con1 = model.createCons(myConshdlr, "my constraint", stickingatnode=True)
model.addConsNode(node, con1) 

```

1) Is using constraint handler the only way to create constraints locally and use addConsNode()?
Is there any simpler way to add constraint at node, like using constraint expression in addCons()?
Such as
```
         for var in self.model.vars:      
               if condition is True:
                  model.addConsNode(var == 0)
```

2) What does  "stickingatnode" parameter in the model.createCons() do? 

Thank you

**Comment by fserra** [comment]
Hi

you can read about stickingatnode [here](https://www.scipopt.org/doc/html/FAQ.php#pricerandnodedata). 

Regarding your other question... mmhmm. Maybe I am wrong here (@mattmilten !) but it seems to me that one can only use a constraint handler. In SCIP you can create a constraint and then add it. In PySCIPOpt, when you create an ExprCons, the only way to get a `Constraint` object from it is (as far as I can see) using `addCons`, which will create the constraint and add it.
Since, `addConsNode` uses a `Constraint` object, you can't call it with an ExprCons.

Mmm, so I think we have `addCons` like that, because we didn't want the users to have to create a constraint an then add it.
Maybe we can add another function to create a constraint? Or should we extend `addConsNode`, `addConsLocal` to also accept ExprCons?
Or am I missing something?

**Comment by purin0604** [comment]
Thank you for the prompt answer.
Making sure the ExprCons is only used in addCons was enough for me for now :)
I might have some more questions about the constraint handler, so I will leave this thread open for a few days.
