### ISSUE TITLE
Behaviour of getObjVal() for infeasible and unbounded problems

### ISSUE THREAD

**Issue by a-schmitt** [SCIP-Interfaces/PySCIPOpt#396]
I was using the nice interface and stumbled upon the behavour, that getObjVal() returns for infeasible problems 0 and for unbounded problems the value of a best found solution before unboundedness was detected. 
This lead to a small bug for me, since I hid the output of SCIP and realized not until later that my model was unbounded.
I was wondering whether return values of +/-float("inf") would be more appropriate.
Another idea would be to raise a warning if either self._bestSol == None or getStatus() returns infeasible.

**Comment by fserra** [comment]
This is bad, sorry. We are now (for some time) a bit unhappy with this `_bestSol` and we were thinking of removing it altogether. However, it will take some time.
Removing it though would force the users to get the best solution and it will make it more likely that they check for the status. So I am not very inclined at this point to add more functionality to this function that should get deleted

**Comment by a-schmitt** [comment]
Hi tanks for the reply!
I did not know that you want to remove _bestSol. Just for clarification: That means you want to also remove getObjVal()?
If you want to keep it I could try and implement the method using self.getBestSol() instead of _bestSol and raising a warning in case of no solution or an unbounded problem.
Otherwise i will just close the issue.

**Comment by a-schmitt** [comment]
Hi tanks for the reply!
I did not know that you want to remove _bestSol. Just for clarification: That means you want to also remove getObjVal()?

If you want to keep it I could try and implement it using self.getBestSol() instead of _bestSol and raising a warning in case of no solution or an unbounded problem.

Otherwise I will close the issue (again) :)

**Comment by fserra** [comment]
mmmm. Yeah, I think we would also remove `getObjVal()`

In SCIP, to get the objective value of a particular solution, one needs to call `SCIPgetSolOrigObj(scip, sol)`. So to use that one would first need to get the solution. My hope would be that if the user is forced to get the solution, then the user would check the status of the problem.
Alternatively, one can call `SCIPgetPrimalbound(scip)` (in pyscipopt `getPrimalbound`). This would just return infinity if the problem is unbounded and -infinity if infeasible.

I don't think it is the job of pyscipopt to check the status of the problem for the user. So, anything that motivates the user not to check the solution status after calling `optimize` is "bad".
Anyway, I think that the examples and test we have are to blame because most of them do not check status.
