### ISSUE TITLE
test_string_poly() in test_nonlinear.py is flaky

### ISSUE THREAD

**Issue by yozw** [SCIP-Interfaces/PySCIPOpt#402]
In 7/100 runs, I'm getting an unexpected optimal objective value, namely 1.69200831463043. The expected objective value is 1.692489081738 (which happened in 93/100 runs). I've only observed this when *not* compiled in debug mode. 

One way to fix this is to increase the tolerance of the test, but I just wanted to check that (a) you can reproduce this, and (b) this is expected.

**Comment by fserra** [comment]
I think this occurs because the constraints can be generated differently. For example, in two runs of the example, I get
```
created nonlinear constraint   [nonlinear] <voldef>: ( +1.5707963267949 * <ncoils> * <coildiam> * <wirediam> * <wirediam> +3.14159265358979 * <coildiam> * <wirediam> * <wirediam> -1 * <volume>) == 0;
```
and
```
created nonlinear constraint   [nonlinear] <voldef>: ( +1.5707963267949 * <coildiam> * <wirediam> * <wirediam> * <ncoils> +3.14159265358979 * <coildiam> * <wirediam> * <wirediam> -1 * <volume>) == 0;
```

Now if the order of the variables is different, then presolving might work differently (for example, if you have `x*y*z` SCIP might decide to make this into a quadratic as `w = x * y` and `w*z`. if you have `y*z*x` then one might obtain `w = y*z` and `w*x`). 
In this particular case, presolving is indeed working differently and this explains the different results.

The reason why the variables are sorted different, I suspect, is because we are using the pointer of the variables to create a dictionary in python and then making a list out of it. In `_addNonlinearCons` you find
```
        variables = {var.ptr():var for term in terms for var in term}
        variables = list(variables.values())
```
I guess we could use something more deterministic than the ptr of the variables, but still I wouldn't know if the conversion from dict to list is always sorted in the same way.

So yeah, the solution right now would be to increase the tolerance if this is failing.

**Comment by yozw** [comment]
I briefly looked into replacing `variables = list(variables.values())` by `variables = sorted(variables.values(), key=lambda var: var.name)`, but no success. I'll change the tolerance to 1.0e-3 in our code base. Would you mind doing the same in this Github repo (I would send you a pull request myself, but as I'm about to go on holiday, I'm a bit short on time).

**Comment by fserra** [comment]
sure
