### ISSUE TITLE
a question about solving speed of MILP problem

### ISSUE THREAD

**Issue by Anyon123** [SCIP-Interfaces/PySCIPOpt#419]
I have a MILP problem, worte in an .lp file.
When I used SCIP to solve it. There is a warning like "Deactivated symmetry handling, since SCIP was built without symmetry detector". The problem was solved after 900s later.
But when I used Gurobi to solve it, it spent like 1 second.
I wonder if the symmetry handling is so important that affect several hundred times of solving time?
And what should I do to reduce the solving time by SCIP?
Thank youu in advance

**Comment by mattmilten** [comment]
This might not even be only due to the missing symmetry. Gurobi is very well-tuned for performance on a very large set of instances. You may be able to achieve comparable performance with SCIP/PySCIPOpt when setting the correct parameters. I suggest you inspect the log files of the two solvers and try to figure out why SCIP takes so much longer. Solving MILPs is a difficult task and sometimes you just have to wait a bit for the solution.
Another approach could be to relax your termination criteria, for example a larger MIP gap might decrease the solving time a lot.

**Comment by Anyon123** [comment]
Thank you very much dear mattmilten, you helps a lot
