### ISSUE TITLE
PySCIPOpt test error

### ISSUE THREAD

**Issue by chenhuims** [SCIP-Interfaces/PySCIPOpt#42]
Dear Developers,

I installed the PySCIPOpt package on two Linux machines by following the instruction below
https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/INSTALL.md
But I encountered the following error 
ImportError: No module named 'pyscipopt.scip'
when I tested the examples by py.test on one machine. The Linux version of this machine is 
CentOS Linux release 7.2.1511
However, I can run the examples on the other Linux machine which is probably Ubuntu. 

Could you give me some hints about how to solve this issue? Thank you very much!!

**Comment by fserra** [comment]
Hey Chen

I don't know what your problem is, so let me discard some of the standard problems

1. Did you use the updated [Makefile.doit](http://scip.zib.de/download/bugfixes/scip-3.2.1/Makefile.doit) for compiling SCIP? You need to replace the Makefile.doit that is shipped with the SCIP Optimization Suit, with that one

2. Are you running the examples from the PySCIPOpt main directory? This will not work

**Comment by mattmilten** [comment]
This issue is inactive and will be closed because @chenhuims is not responding.
