### ISSUE TITLE
get dual solution

### ISSUE THREAD

**Issue by martihj** [SCIP-Interfaces/PySCIPOpt#66]
The below code results in a segmentation fault error at the last line. If makes any difference I am running python 3.5 on Ubuntu. Any idea why this happens?

    import pyscipopt as scp
    Mod=scp.Model()
    Mod.setPresolve(0)
    Mod.hideOutput()
    x=Mod.addVar(ub=3,name="x")
    y=Mod.addVar(ub=4,name="y")
    c1=Mod.addCons(x+y<=3,"C1")
    Mod.setObjective(x+y, "maximize")
    Mod.optimize()
    print(Mod.getObjVal())
    print(Mod.getDualsolLinear(c1)) # Error

Error message: `Segmentation fault (core dumped)`

**Comment by fserra** [comment]
Interesting. I get `python: src/scip/cons_linear.c:17907: SCIPgetDualsolLinear: Assertion `cons != NULL' failed`
so the constraint is NULL... I am guessing that since the constraint is original, the code is asking for the transformed constraint and then calling getdualsollinear with the transformed constraint. However, the transformed constraint shouldn't exist because the problem is already solved... then this should never work and actually the example `lo_wines` (which also calls that method) fails with the same error.

thanks for reporting we will have a look

**Comment by mattmilten** [comment]
You need to disable presolving to have access to the dual values:

    Mod.setPresolve(scp.SCIP_PARAMSETTING.OFF)

**Comment by mattmilten** [comment]
Apparently, the `0` is not always guaranteed to be translated correctly into the corresponding SCIP enumerator. We will fix `test_pricer.py` as well.

**Comment by mattmilten** [comment]
`test_pricer` is using the correct value already: https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/tests/test_pricer.py#L17

**Comment by fserra** [comment]
@mattmilten did you commit did on your own fork? I don't have it in pyscipot
