### ISSUE TITLE
Dual solution after recalculation

### ISSUE THREAD

**Issue by martihj** [SCIP-Interfaces/PySCIPOpt#75]
After I resolve a problem the dual values of a constraint is not updated, i.e. take a look at the following code: 

    import pyscipopt as scp
    Mod=scp.Model()
    Mod.setMaximize()
    Mod.setPresolve(scp.SCIP_PARAMSETTING.OFF)
    Mod.hideOutput()
    x=Mod.addVar(ub=3,name="x",obj=0.1,vtype="C")
    y=Mod.addVar(ub=3,name="y",obj=1)
    c=Mod.addCons(x+y<=3,"C1")
      
    Mod.optimize()
    print("SCIP")
    print("obj: ", Mod.getObjVal())
    print(x.name,Mod.getVal(x))
    print(y.name,Mod.getVal(y))
    print("pi: ",Mod.getDualsolLinear(c))    
    Mod.freeTransform() 
    Mod.chgRhs(c,2)
    
    Mod.optimize()
    print("obj: ", Mod.getObjVal())
    print(x.name,Mod.getVal(x))
    print(y.name,Mod.getVal(y))
    print("pi: ",Mod.getDualsolLinear(c))    

Output:

    SCIP
    obj:  3.0
    x 0.0
    y 3.0
    pi:  0.1
    obj:  2.0 
    x 0.0
    y 2.0
    pi:  0.1

But clearly `pi` should be 1 after the constraint is tightened. If I also remove `x` from the objective function I receive the following: `Warning: no dual solution available for constraint C1`

Is this a bug or do I need to call some update function? I can just use another LP solver, just curious why I observe this behavior.

Thanks for all the help guys :)

**Comment by fserra** [comment]
This is actually weird. It is not a problem of updating the constraint. If you set the problem with `x+y <= 2` to begin with, the same 0.1 dual value appears.

For your second problem, this happens because the constraint is actually a bound constraint and so `scip` is removing it (even if presolving is off). I am guessing we are going to fix this on the next release (if not already fixed) but this takes some time to appear on the interface. We could, of course, have a workaround for the meantime, but we are still undecided about this.

thanks for reporting

**Comment by mattmilten** [comment]
You need to disable propagation as well. I will add a new method that will do that. see #76

**Comment by fserra** [comment]
The problem was that SCIP was propagating the constraint and so the bounds were changed from 3 to 2, making the dual redundant

**Comment by mattmilten** [comment]
I updated the README to include a note about dual innformation. #80 solves the issue
