### ISSUE TITLE
constraint handler: clean-up, test and example/documentation

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/PySCIPOpt#9]
The code in the `.pxi` should be checked and (automatically) tested with an example. The example can also serve as documentation.

**Comment by fserra** [comment]
I am unsure how to document this. On one hand we can just reference to SCIP's documentation.  
However, this is not sufficient, since stuff like "stores a pointer to the constraint in cons", etc, don't really apply to Python  
Also, there are things that are particularly to the interface, for instance, returning everything in dictionaries. Is this documented anywhere? @mattmilten ?

**Comment by mattmilten** [comment]
No the dictionary return is not (yet) documented. Any ideas where to put this?

**Comment by fserra** [comment]
in writing new plugins I would think is natural

**Comment by fserra** [comment]
I'll create a branch here to do this, so that we all can contribute, is that ok???

**Comment by mattmilten** [comment]
I don't think we need a branch for this. You can just edit the docu.

**Comment by fserra** [comment]
ICMS is long go. What about this issue? is it still relevant ?

**Comment by leethargo** [comment]
Well, an example exists already, so you can close it.
